### ISSUE TITLE
Suggest: add tests and CI

### ISSUE THREAD

**Issue by richelbilderbeek** [xiaolei-lab/SIMER#2]
Dear SIMER maintainers, hi @XiaoleiLiuBio,

SIMER seems to have much potential and I consider becoming an early user of it. What holds me back are the lack of tests and the absence of a continuous integration service (such as GitHub Actions).

Are there plans to add these, so others can be convinced of the correctness of SIMER? If yes, I do volunteer to help if requested.

**Comment by XiaoleiLiuBio** [comment]
Thank you very much for your suggestions. We agree that tests are very important. Recently, we have made abundant tests on SIMER, e.g., to test if SIMER can simulate a phenotype with a given heritability and variance, and also compared the simulation accuracy with existing tools. After we finished the main functions, we will try to add the tests, maybe in a couple of months.

**Comment by richelbilderbeek** [comment]
Happy to hear that tests are valued! 

> Recently, we have made abundant tests on SIMER

I cannot find these in the repo. Is there a seperate repo just for testing?

And what about Continuous Integration?

**Comment by XiaoleiLiuBio** [comment]
We haven't added the tests in the repo at present. The tests will be added after we finished the tests.

I didn't have any experience with CI, and will think about it later.

**Comment by richelbilderbeek** [comment]
> The tests will be added after we finished the tests.

Nice, looking forward to that!

If you want, I can volunteer to add CI, as it will not take too long for me.

In any case, go ahead and close this Issue after reading this :+1:

**Comment by XiaoleiLiuBio** [comment]
I will let you know if we need any help from you. Thank you in advance!
