### ISSUE TITLE
Modelling traits with different distributions 

### ISSUE THREAD

**Issue by m-hrachov** [xiaolei-lab/SIMER#4]
Hi! I see I could model different underlying distributions of QTLs, but is it possible to model the trat that has gamma or beta (anything besides normal) distribution? Thank you.

**Comment by Foredawnbio** [comment]
Thank you for using Simer. You will get gamma or beta distubution follow these links:
[Generate phenotype controlled by QTNs subject to Gamma distribution](https://github.com/xiaolei-lab/SIMER#generate-phenotype-controlled-by-QTNs-subject-to-gamma-distribution);
[Generate phenotype controlled by QTNs subject to Beta distribution](https://github.com/xiaolei-lab/SIMER#generate-phenotype-controlled-by-QTNs-subject-to-beta-distribution).

**Comment by m-hrachov** [comment]
Hi and thank you.
The question is not answered. 
The phenotype is _controlled_ by some non-normal distribution, but the distribution of phenotypic records stays _normal_ all the time (i.e. barplot of phenotypic values). 
I am interested in modeling a trait that has non-normal phenotypic distribution (e.g. disease scores). Is there a way to do so?

**Comment by Foredawnbio** [comment]
Hi and I understand your question now.
You know Y = G + E, where Y is phenotype, G is genetic value, and E is residual. There are 2 ways to simulate phenotype with a skew distribution:
1) sampling a small number of SNPs as QTNs with a skew distribution (the distribution of 0, 1, 2 is skew), and multiplied by the QTN effects with normal distribution to get a skew G;
2) keeping G normal, but sampling a skew residual E.

**Comment by m-hrachov** [comment]
Okay, thank you for your help! This works.
