### ISSUE TITLE
Numeric output format does not produce genotype matrix

### ISSUE THREAD

**Issue by m-hrachov** [xiaolei-lab/SIMER#5]
PLINK output works well, numeric does not. Option: save a genotype matrix myself.

Minimal reproducible example:

``` R
SP <- param.simer(
  # SP = SP, # uncomment it when users already have a 'SP'
  out = "simer",
  outpath = getwd(),
  out.format = "numeric"
)

# Run Simer
SP <- simer(SP)
```

**Comment by Foredawnbio** [comment]
I'm sorry for being three weeks late. I ran above minimal reproducible example and get a normal resuts.

Maybe you think Simer outputs a TXT with genotype data. Simer outputs genotype matrix with bigmemory format which you load genotype matrix by "geno <- bigmemory::attach.big.matrix('simer.geno.desc')".

Does it solve your problem?
